image: ubuntu/latest
sources:
- https://git.sr.ht/~tsileo/blobstash
- https://git.sr.ht/~tsileo/blobstash-python
packages:
- python3-dev
- python3-pip
tasks:
- go: |
   mkdir go
   export GOPATH=/home/build/go
   wget -q https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
   sudo tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz
- blobstash: |
   export GOPATH=/home/build/go
   cd blobstash
   /usr/local/go/bin/go install -mod=vendor
- lint: |
   cd blobstash-python
   pip3 install --progress-bar off black flake8 mypy
   python3 -m black --check .
   python3 -m flake8 blobstash
   python3 -m mypy --ignore-missing-imports blobstash
- test: |
   export PATH=$PATH:$GOPATH/bin/
   cd blobstash-python
   pip3 install .
   pip3 install --progress-bar off -r dev-requirements.txt
   python3 -m pytest -k test_utils -v
