---
kind: pipeline
name: default
steps:
  - name: lint
    image: python:3
    commands:
      - pip install black flake8 mypy
      - black --check .
      - flake8 blobstash
      - mypy --ignore-missing-imports blobstash

  - name: build_blobstash
    image: golang:latest
    commands:
      # Install BlobStash
      - export GOPATH="`pwd`/go"
      - mkdir -p $GOPATH/bin
      - git clone --depth=1 https://github.com/tsileo/blobstash.git bs && cd bs && go build -mod=vendor && cp -r blobstash $GOPATH/bin && cd - && rm -rf bs

  - name: test
    image: python:3
    commands:
      - export GOPATH="`pwd`/go"
      - export PATH="$GOPATH/bin:$PATH"
      # Setup the Python package
      - python setup.py install
      - pip install -r dev-requirements.txt
      - pytest -k test_utils -v
---
kind: signature
hmac: b72a2c9fee8d604cbb1fd0f878a8c8bb3cd7ee7ee43d2d4a34adbb9b8258c67f

...
