language: python
python:
  - "3.6"
install:
  # Install BlobStash
  - export GOPATH="${TRAVIS_BUILD_DIR}/go/"
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.12 bash)"
  - go get github.com/tsileo/blobstash
  - export PATH="${TRAVIS_BUILD_DIR}/go/bin:$PATH"
  # Setup the Python package
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install
script:
  - pytest -v
  - mypy --ignore-missing-imports blobstash

